title: My GitHub Pages Blog
description: This is my personal blog built with GitHub Pages
baseurl: ""
url: "https://3huo.github.io"

author:
  name: Your Name
  email: your-email@example.com
  social:
    github: your-username
    twitter: your-twitter

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num"

header_pages:
  - index.md
  - about.md

#remote_theme: mmistakes/minimal-mistakes@3.4.1
theme: jekyll-theme-merlot

# 评论系统占位（可配置 Disqus）
disqus:
  shortname: your-disqus-shortname

# Markdown & syntax highlighting
markdown: kramdown
highlighter: rouge