title: My GitHub Pages Blog
description: This is my personal blog built with GitHub Pages
baseurl: ""
url: "https://3huo.github.io"
plugins:
  - jekyll-remote-theme
remote_theme: mmistakes/minimal-mistakes@4.24.0
author:
  name: Yancheng Wang
  email: your-email@example.com
markdown: kramdown
theme: null